Adding time based run and multiple instance support for the client
Node-DC/Node-DC-EIS pull request #28
Opened 2017-06-08 17:29 UTC by priyankasprakash

Client changes to support time based run.
Added a new script to post process data for time based run.
Refactored code to have common functions in util.py.

2017-06-08 20:26 UTC, egalli requested changes

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/util.py
> +def getCurrentTime():
Since we are refactoring getCurrentTime, do you mind rename it to get_current_time()? Traditionally, python uses underscores instead of camelCase. Same for currentTime.

Either way, I don't care that much. I just like consistency. :)

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_process_output.py
> +        print("Couldnot Open templog file for writing")
We should probably exit/return out of the function here. Otherwise, the next lines will try to print to an undefined file pointer.

Small note, shouldn't it be "Could not open templog file for writing"?

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_process_output.py
> +        if(os.path.exists(os.path.join(results_dir,"tempfile_"+str(file_cnt)))):
Maybe better to extract "os.path.join(results_dir,"tempfile_"+str(file_cnt)" into a variable and using in lines 55 and 58?

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_process_output.py
> +            print ("[%s] Processing Output File tempfile_[%d]." % (time.strftime("%d-%m-%Y %H:%M:%S"),file_cnt))
These prints are directly calling strftime. Did you forget to add them to the commit? If not, do mind changing them to use getCurrentTime/get_current_time?

We could also create a print_with_date (or something better) function that basically does print '[{}] {}'.format(utils.get_current_time(), data). But it might no be worth the effort at that point.

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_testurls.py
> +import util as util
"as util" is redundant

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_process_output.py
> +import util as util
"as util" is redundant

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_testurls.py
> +          log = open(os.path.join(log_dir,"tempfile_"+str(file_cnt)),"w")
same as line 50 on node_dc_eis_process_output.py

Since this line also repeats on line 272 it might make sense to extract it as,
```python
if init and time.time() - start_time > float(interval):
    file_cnt += 1
    init = False

if not init:
    start_time = time.time()
    try:
        log = ...
```

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/runspec.py
> +  if(requests_done):
Why are we checking requests_done right after we set it?

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/runspec.py
> +  if(requests_done):
Same as line 1046

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/runspec.py
> +  if sys.platform != "win32":
Out of curiosity, why are we using POSIX signals?

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/util.py
> +      print >> log, phase+","+str(request_num)+","+str(url)+","+str(start)+","+str(end)+","+str(response_time)
Since they are the same, lines 55, 58, and 60 can be extracted out of the if statements and moved to just before the call to flush()

2017-06-08 20:26 UTC, egalli commented on Node-DC-EIS-client/util.py
> +
might want to add an empty line at the end :)

2017-06-09 00:30 UTC, priyankasprakash commented on Node-DC-EIS-client/runspec.py
> +  if sys.platform != "win32":
This is for Windows compatibility.

2017-06-09 17:07 UTC, egalli commented on Node-DC-EIS-client/runspec.py
> +  if sys.platform != "win32":
Looks like the else part is for windows. I'm just not sure why we need signals. It seems like the windows version would work for both.

2017-06-09 17:12 UTC, uttampawar approved these changes
LGTM

2017-06-09 17:14 UTC, uttampawar commented
@egalli Can you you have another look at the change, please? I'll merge it if you don't any more comments.

2017-06-09 17:45 UTC, egalli commented
I just had some questions regarding the use of signals. Other than that, it looks good to me.

2017-06-11 16:04 UTC, uttampawar commented
Is there any update about use of signals?

2017-06-12 17:12 UTC, priyankasprakash commented
I am working on making changes to run without signals as suggested by Enrico. I will test and submit the changes.

2017-06-12 20:55 UTC, egalli approved these changes

2017-06-12 20:57 UTC, egalli commented
Looks good. Also, thanks for fixing those typos. 😄

2017-06-13 00:41 UTC, uttampawar reviewed
LGTM

2017-06-13 00:42 UTC, merged