Fixing last name count logic for database loading
Node-DC/Node-DC-EIS pull request #52
Opened 2017-08-01 05:48 UTC by priyankasprakash

2017-08-01 16:30 UTC, uttampawar reviewed
@priyankasprakash Has this been tested? Specifically the config.json and runspec.py changes. You should have made two separate PR's. One for client and another for Server.
Did you get a chance to do a long run? How does result looks like for the long run?

2017-08-02 01:15 UTC, egalli requested changes

2017-08-02 01:15 UTC, egalli commented on Node-DC-EIS-cluster/controllers/loader.js
> +  if (lnames.length < lastnamecount) {
I think it should be <= instead of <

2017-08-02 01:15 UTC, egalli commented on Node-DC-EIS-cluster/controllers/loader.js
> +      var new_name = lnames[idx]+ii.toString();
.toString() is redundant. JS automatically converts Numbers to Strings when concatenating them to a String

2017-08-02 16:51 UTC, uttampawar commented on Node-DC-EIS-cluster/controllers/loader.js
> +      var new_name = lnames[idx]+ii.toString();
@egalli @priyankasprakash Even though JS converts number to strings automatically, I would rather have a clean use of API. Use of Number.toString() API is a clean way to use it.

2017-08-02 16:51 UTC, uttampawar commented on Node-DC-EIS-cluster/controllers/loader.js
> +  if (lnames.length < lastnamecount) {
Agree.

2017-08-14 16:22 UTC, uttampawar commented
LGTM.

2017-08-15 23:29 UTC, merged