Client changes and bug fixes
Node-DC/Node-DC-EIS pull request #54
Opened 2017-08-17 17:31 UTC by priyankasprakash

2017-08-18 22:32 UTC, egalli requested changes

2017-08-18 22:32 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_testurls.py
> +      content_len = len(r.content)
please extract the length calculation into a separate function and call it from the post and get

2017-08-18 22:32 UTC, egalli commented on Node-DC-EIS-client/node_dc_eis_testurls.py
> +    delete_url(url,url_type,request_num,log,phase)
the github seems to be complaining about the lack of new line at the end. Should we add one?

2017-08-24 18:26 UTC, uttampawar commented
@priyankasprakash Any update on the fix?

2017-08-24 19:51 UTC, priyankasprakash commented on Node-DC-EIS-client/node_dc_eis_testurls.py
> +    delete_url(url,url_type,request_num,log,phase)
It complains even if I add a new line. Any idea how to fix this?

2017-08-24 20:20 UTC, egalli approved these changes

2017-08-24 20:27 UTC, merged